name: flutter_brand_icons
description: A collection of simply beautiful open source icons. Each icon is designed on a 24x24 grid with an emphasis on simplicity, consistency and usability.
version: 0.0.1
author: Nikhil Anand <nick.muj.programmer@gmail.com>
homepage: https://github.com/muj-programmer/flutter_brand_icons

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  recase: ^2.0.1

flutter:
  fonts:
    - family: BrandIcons
      fonts:
        - asset: fonts/brands.ttf
